import Head from "next/head";
import { sourcebitDataClient } from "sourcebit-target-next";
import { toObjectId, toFieldPath } from "@stackbit/annotations";
import { withRemoteDataUpdates } from "sourcebit-target-next/with-remote-data-updates";
import styles from "../styles/Home.module.css";

export function DynamicPage({ site, page }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{site.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} {...toObjectId(page.__metadata.id)}>
        <h1 className={styles.title} {...toFieldPath("title")}>
          {page.title}
        </h1>
        <p className={styles.description} {...toFieldPath("body")}>
          {page.body}
        </p>
      </main>
    </div>
  );
}

export async function getStaticProps({ params }) {
  const pagePath =
    typeof params?.slug === "string"
      ? params?.slug
      : "/" + (params?.slug || []).join("/");
  const props = await sourcebitDataClient.getStaticPropsForPageAtPath(pagePath);
  return { props };
}

export async function getStaticPaths() {
  const paths = await sourcebitDataClient.getStaticPaths();
  return {
    paths,
    fallback: false,
  };
}

export default withRemoteDataUpdates(DynamicPage);
