name: ThemeConfig
label: Theme configuration
singleInstance: true
type: data
fields:
  - type: enum
    name: theme
    label: Theme
    required: true
    default: light
    options:
      - light
      - dark
      - cupcake
      - bumblebee
      - emerald
      - corporate
      - synthwave
      - retro
      - cyberpunk
      - valentine
      - halloween
      - garden
      - forest
      - aqua
      - lofi
      - pastel
      - fantasy
      - wireframe
      - black
      - luxury
      - dracula
      - cmyk
